# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 17:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=30, verbose_name='昵称')),
                ('realname', models.CharField(blank=True, max_length=30, verbose_name='姓名')),
                ('blog', models.URLField(blank=True, null=True, verbose_name='博客')),
                ('signature', models.CharField(blank=True, max_length=254, null=True, verbose_name='签名')),
                ('student_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='学号')),
                ('hdu_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='HDU Online Judge 用户名')),
                ('cf_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='Codeforces 用户名')),
                ('bc_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='Best Coder 用户名')),
                ('tc_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='Top Coder 用户名')),
                ('accept_problem_count', models.IntegerField(default=0, verbose_name='通过题目数')),
                ('accept_count', models.IntegerField(default=0, verbose_name='通过提交次数')),
                ('submit_count', models.IntegerField(default=0, verbose_name='提交次数')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('account',),
            },
        ),
    ]
