# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20170124_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='motto',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='签名'),
            preserve_default=False,
        ),
    ]
